# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: App Lint
      run: echo "Lint"

    - name: App Test
      run: echo "Test"

    - name: Packer Validate
      run: packer validate packer.json

    - name: Packer Build
      run: packer build packer.json
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_KEY_SECRET }}
          AWS_DEFAULT_REGION: us-east-1
    - name: Get AMI ID
      run: |
            sudo apt-get -y upgrade
            pip install setuptools
            pip install --upgrade setuptools
            pip3 install boto3
            pip3 install pytz
            python3 asg.py
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_KEY_SECRET }}
          AWS_DEFAULT_REGION: us-east-1



