
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Lint
      run: echo "Lint"

    - name: Test
      run: echo "Test"

    - name: Validate AMI
      run: packer validate packer.json

    - name: Build AMI
      run: packer build packer.json
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_KEY_SECRET }}
          AWS_DEFAULT_REGION: us-east-1
    - name: Refresh ASG
      run: |
            sudo apt-get -y upgrade
            pip3 install setuptools
            pip3 install --upgrade setuptools
            pip3 install boto3
            pip3 install pytz
            python3 asg.py
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_KEY_SECRET }}
          AWS_DEFAULT_REGION: us-east-1



