
name: Infrastructure

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Terraform Init
      run: terraform init -reconfigure ./infra
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_KEY_SECRET }}
        AWS_DEFAULT_REGION: us-east-1

    - name: Terraform Validate
      run: terraform validate ./infra

    - name: Terraform Build
      run: terraform apply --auto-approve ./infra
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_KEY_SECRET }}
          AWS_DEFAULT_REGION: us-east-1



