# This is a basic workflow to help you get started with Actions

name: Infra

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
    repository_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Terraform Validate
      run: tf validate ./infra

    - name: Terraform Build
      run: tf apply --auto-approve ./infra
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_KEY_SECRET }}
          AWS_DEFAULT_REGION: us-east-1



